In [ ]:
# the final accuracy comes out as 88.72% and keras module has been used for the model. 
# data is first 'prepared' and then evaluated by ANN model as follows:

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('cities.csv')

In [3]:
dataset

Date Location MinTemp MaxTemp Rainfall Evaporation Sunshine  \
0       2008-12-01   Albury    13.4    22.9      0.6         NaN      NaN   
1       2008-12-02   Albury     7.4    25.1      0.0         NaN      NaN   
2       2008-12-03   Albury    12.9    25.7      0.0         NaN      NaN   
3       2008-12-04   Albury     9.2    28.0      0.0         NaN      NaN   
4       2008-12-05   Albury    17.5    32.3      1.0         NaN      NaN   
5       2008-12-06   Albury    14.6    29.7      0.2         NaN      NaN   
6       2008-12-07   Albury    14.3    25.0      0.0         NaN      NaN   
7       2008-12-08   Albury     7.7    26.7      0.0         NaN      NaN   
8       2008-12-09   Albury     9.7    31.9      0.0         NaN      NaN   
9       2008-12-10   Albury    13.1    30.1      1.4         NaN      NaN   
10      2008-12-11   Albury    13.4    30.4      0.0         NaN      NaN   
11      2008-12-12   Albury    15.9    21.7      2.2         NaN      NaN   
12      2008-12-13   Albury    15.9    18.6     15.6         NaN      NaN   
13      2008-12-14   Albury    12.6    21.0      3.6         NaN      NaN   
14      2008-12-16   Albury     9.8    27.7      NaN         NaN      NaN   
15      2008-12-17   Albury    14.1    20.9      0.0         NaN      NaN   
16      2008-12-18   Albury    13.5    22.9     16.8         NaN      NaN   
17      2008-12-19   Albury    11.2    22.5     10.6         NaN      NaN   
18      2008-12-20   Albury     9.8    25.6      0.0         NaN      NaN   
19      2008-12-21   Albury    11.5    29.3      0.0         NaN      NaN   
20      2008-12-22   Albury    17.1    33.0      0.0         NaN      NaN   
21      2008-12-23   Albury    20.5    31.8      0.0         NaN      NaN   
22      2008-12-24   Albury    15.3    30.9      0.0         NaN      NaN   
23      2008-12-25   Albury    12.6    32.4      0.0         NaN      NaN   
24      2008-12-26   Albury    16.2    33.9      0.0         NaN      NaN   
25      2008-12-27   Albury    16.9    33.0      0.0         NaN      NaN   
26      2008-12-28   Albury    20.1    32.7      0.0         NaN      NaN   
27      2008-12-29   Albury    19.7    27.2      0.0         NaN      NaN   
28      2008-12-30   Albury    12.5    24.2      1.2         NaN      NaN   
29      2008-12-31   Albury    12.0    24.4      0.8         NaN      NaN   
...            ...      ...     ...     ...      ...         ...      ...   
142211  2017-05-26    Uluru    14.3    27.6      0.4         NaN      NaN   
142212  2017-05-27    Uluru     9.3    28.0      0.0         NaN      NaN   
142213  2017-05-28    Uluru     8.0    24.6      0.0         NaN      NaN   
142214  2017-05-29    Uluru    12.7    22.2      0.0         NaN      NaN   
142215  2017-05-30    Uluru     9.4    22.7      0.0         NaN      NaN   
142216  2017-05-31    Uluru     5.4    20.5      0.0         NaN      NaN   
142217  2017-06-01    Uluru     5.6    19.4      0.0         NaN      NaN   
142218  2017-06-02    Uluru     1.5    19.2      0.0         NaN      NaN   
142219  2017-06-03    Uluru     3.8    19.8      0.0         NaN      NaN   
142220  2017-06-04    Uluru     4.5    18.8      0.0         NaN      NaN   
142221  2017-06-05    Uluru     4.9    20.7      0.0         NaN      NaN   
142222  2017-06-06    Uluru     1.2    20.8      0.0         NaN      NaN   
142223  2017-06-07    Uluru     0.5    21.7      0.0         NaN      NaN   
142224  2017-06-08    Uluru     4.0    20.0      0.0         NaN      NaN   
142225  2017-06-09    Uluru     3.4    19.8      0.0         NaN      NaN   
142226  2017-06-10    Uluru     3.2    18.6      0.0         NaN      NaN   
142227  2017-06-11    Uluru     2.4    19.1      0.0         NaN      NaN   
142228  2017-06-12    Uluru     5.1    19.7      0.0         NaN      NaN   
142229  2017-06-13    Uluru     2.5    21.2      0.0         NaN      NaN   
142230  2017-06-14    Uluru     2.3    21.4      0.0         NaN      NaN   
142231  20

In [4]:
X = dataset.iloc[:, :-1].values

In [5]:
y = dataset.iloc[:, 23].values

In [13]:
data=dataset.values

In [14]:
data

array([['2008-12-01', 'Albury', '13.4', ..., 'No', '0.0', 'No'],
       ['2008-12-02', 'Albury', '7.4', ..., 'No', '0.0', 'No'],
       ['2008-12-03', 'Albury', '12.9', ..., 'No', '0.0', 'No'],
       ...,
       ['2017-06-22', 'Uluru', '3.6', ..., 'No', '0.0', 'No'],
       ['2017-06-23', 'Uluru', '5.4', ..., 'No', '0.0', 'No'],
       ['2017-06-24', 'Uluru', '7.8', ..., 'No', '0.0', 'No']],
      dtype=object)

In [15]:
'from sklearn.cluster import KMeans'
from sklearn import preprocessing

In [16]:
dataset.fillna(0, inplace = True)

In [17]:
dataset = dataset.astype("category")

In [18]:
df=dataset

In [19]:
df=df.drop(columns=['Evaporation', 'Sunshine','Date','Location'])

In [20]:
# The directions of wind and other string data not including the names are converted to integers and model is evaluated after splitting the data
def handle_non_numerical_data(df):
    columns = df.columns.values

    for column in columns:
        text_digit_vals = {}
        def convert_to_int(val):
            return text_digit_vals[val]

        if df[column].dtype != np.int64 and df[column].dtype != np.float64:
            column_contents = df[column].values.tolist()
            unique_elements = set(column_contents)
            x = 0
            for unique in unique_elements:
                if unique not in text_digit_vals:
                    text_digit_vals[unique] = x
                    x+=1

            df[column] = list(map(convert_to_int, df[column]))

    return df

df = handle_non_numerical_data(df)

In [21]:
df.head()

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
0      184      340       532           10             25          10   
1      260      473       590           16             25          13   
2        3      362       590           11             63          10   
3      323       13       590            1             28           3   
4      258      333       439           10             17           1   

   WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0          16            44            21           38           51   
1          11            34            17            8           98   
2          11            31            33           28           12   
3           8            41             2           87           63   
4           9            33            45           65           87   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0          232          338         4         0      203      477          1   
1          304          185         0         0      277        4          1   
2          320          529         0         8      172      407          1   
3          275          192         0         0        3      376          1   
4          531          431         9         5      202       69          1   

   RISK_MM  RainTomorrow  
0      591             0  
1      591             0  
2      591             0  
3      438             0  
4      634             0

In [22]:
df

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
0           184      340       532           10             25          10   
1           260      473       590           16             25          13   
2             3      362       590           11             63          10   
3           323       13       590            1             28           3   
4           258      333       439           10             17           1   
5           172       72       633           16              1          10   
6            10      251       590           10             16          12   
7           253      148       590           10             27           7   
8           262      474       590           12             39           3   
9            63      131        42           10             31           5   
10          184       10       590            5             44           7   
11           30       38       507           17              5           2   
12           30      387       104           10             58          13   
13          183      196        92           13             25          10   
14          116      389         0           16             16           0   
15           42      315       590            2             22           4   
16           82      340       606           10             19           6   
17          375      396       223            7              2          11   
18          116      303       590            7             46           3   
19          101       94       590            6             28           3   
20          381      487       590            1              2           2   
21          165      134       590           16             17          10   
22          207      350       590            5             30          15   
23          183      319       590           10              2           8   
24           77       30       590           11             27           3   
25          180      487       590           11              8           0   
26          358      486       590           16             60           6   
27          351      363       590           16             63           9   
28          342      284       301           16             16          11   
29           79      310       478           10              4          16   
...         ...      ...       ...          ...            ...         ...   
142211       10       93        83           16              4           0   
142212      228       13       590           10             31           4   
142213      352      358       590            8             30           3   
142214      275      431       590            8             20           8   
142215      193      447       590            8             27           3   
142216      136      208       590            8             63           8   
142217       61      296       590            8              2           8   
142218      274      183       590            8             20          15   
142219      133      160       590            2              4          15   
142220      105      287       590            8              5          15   
142221      232      179       590            8             20          15   
142222      166        3       590            8              2          15   
142223      167       38       590            8              2          15   
142224      112       68       590            3              4          15   
142225      238      160       590            8              2          15   
142226      178      387       590            8             63          15   
142227      334      112       590            8             30           3   
142228       88      449       590            8             63          15   
142229      230       56       590            2             27          15   
142230      279      433      

In [23]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 19].values

In [24]:
X

array([[184, 340, 532, ..., 477,   1, 591],
       [260, 473, 590, ...,   4,   1, 591],
       [  3, 362, 590, ..., 407,   1, 591],
       ...,
       [ 48, 145, 590, ..., 268,   1, 591],
       [136,  49, 590, ..., 465,   1, 591],
       [ 67, 106, 590, ..., 422,   1, 591]], dtype=int64)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [26]:
len(X_train[0])

19

In [27]:
y_test

array([1, 1, 1, ..., 0, 0, 1], dtype=int64)

In [28]:
#X = np.array(df.drop(['RainTomorrow'], 1).astype(float))
#y = np.array(df['RainTomorrow'])
#X = preprocessing.scale(X)
#clf = KMeans(n_clusters=2)
#clf.fit(X)

In [29]:
#correct = 0

#for i in range(len(X)):
#    predict_me = np.array(X[i].astype(float))
#    predict_me = predict_me.reshape(-1, len(predict_me))
#    prediction = clf.predict(predict_me)
#    if prediction[0] == y[i]:
#        correct += 1

#print(correct/len(X))

In [30]:
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [31]:
classifier = Sequential()
#First Hidden Layer
classifier.add(Dense(10, activation='relu', kernel_initializer='random_normal', input_dim=19))
#Second  Hidden Layer
classifier.add(Dense(9, activation='relu', kernel_initializer='random_normal'))
#Output Layer
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

W0723 20:26:47.892284  9040 deprecation_wrapper.py:119] From d:\anaconda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0723 20:26:48.696480  9040 deprecation_wrapper.py:119] From d:\anaconda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0723 20:26:48.885296  9040 deprecation_wrapper.py:119] From d:\anaconda\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py:4115: The name tf.random_normal is deprecated. Please use tf.random.normal instead.



In [34]:
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=10, epochs=5)
eval_model=classifier.evaluate(X_train, y_train)
eval_model

Epoch 1/5
113792/113792 [==============================] - 21s 187us/step - loss: 0.2967 - acc: 0.8811
Epoch 2/5
113792/113792 [==============================] - 21s 185us/step - loss: 0.2915 - acc: 0.8809
Epoch 3/5
113792/113792 [==============================] - 21s 183us/step - loss: 0.2876 - acc: 0.8811
Epoch 4/5
113792/113792 [==============================] - 21s 182us/step - loss: 0.2839 - acc: 0.8820
Epoch 5/5
113792/113792 [==============================] - 3s 28us/step


[0.27639248050305115, 0.8848073678290214]

In [35]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[20733  1338     0]
 [ 1868  4499     0]
 [   11     0     0]]
